# Generated by Django 5.2.8 on 2025-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='dynamicqrtoken',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
