# Generated by Django 5.2.8 on 2025-11-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_dynamicqrtoken_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
