# Generated by Django 5.2.8 on 2025-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_session_creator_alter_session_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sso_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
