# Generated by Django 5.2.8 on 2025-11-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_sso_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='is_active',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=50),
        ),
    ]
