# Generated by Django 5.2.8 on 2025-11-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_organizationmember_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What is your role?'),
        ),
    ]
