# Generated by Django 5.2.8 on 2025-11-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsetting',
            name='check_in_window_minutes',
            field=models.IntegerField(default=0, help_text='Time (in minutes) after session start time that check-in is allowed. 0 = No time limit.'),
        ),
    ]
