# Generated by Django 5.2.8 on 2025-11-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sessionsetting_check_in_window_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionsetting',
            name='is_location_required',
        ),
        migrations.RemoveField(
            model_name='sessionsetting',
            name='radius_meters',
        ),
        migrations.RemoveField(
            model_name='sessionsetting',
            name='required_latitude',
        ),
        migrations.RemoveField(
            model_name='sessionsetting',
            name='required_longitude',
        ),
    ]
