# Generated by Django 5.2.8 on 2025-11-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_sessionsetting_is_location_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionsetting',
            name='is_location_required',
            field=models.BooleanField(default=False),
        ),
    ]
