# Generated by Django 5.2.8 on 2025-11-15 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sessionsetting_is_location_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null for personal sessions.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
