# Generated by Django 5.2.8 on 2025-11-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_session_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionsetting',
            name='check_in_window_minutes',
        ),
    ]
