# Generated by Django 5.2.8 on 2025-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emailverificationcode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.AddField(
            model_name='sessionsetting',
            name='check_in_window_minutes',
            field=models.IntegerField(default=0, help_text='Time (in minutes) after session start time that check-in is allowed. 0 = No time limit.'),
        ),
    ]
