# Generated by Django 5.2.8 on 2025-11-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_emailverificationcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.session')),
                ('template_file', models.FileField(help_text='Upload a blank PDF certificate template', upload_to='certificate_templates/')),
                ('name_x_position', models.IntegerField(default=200, help_text='X coordinate for attendee name (pixels from left)')),
                ('name_y_position', models.IntegerField(default=400, help_text='Y coordinate for attendee name (pixels from bottom)')),
                ('font_name', models.CharField(choices=[('Helvetica', 'Helvetica'), ('Helvetica-Bold', 'Helvetica Bold'), ('Times-Roman', 'Times Roman'), ('Times-Bold', 'Times Bold'), ('Courier', 'Courier')], default='Helvetica-Bold', max_length=50)),
                ('font_size', models.IntegerField(default=24, help_text='Font size for attendee name')),
                ('font_color', models.CharField(default='#000000', help_text='Hex color code (e.g., #000000 for black)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.attendancerecord')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='generated_certificates/')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True, help_text='Error message if email failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
