# Generated by Django 5.2.8 on 2025-12-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_certificatetemplate_generatedcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If unchecked, certificates will NOT be sent automatically.'),
        ),
    ]
