from __future__ import annotations

from io import BytesIO

from django.template.defaultfilters import date as _date_format
from django.utils import timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from ..models import AttendanceRecord, Session, SessionSetting


def build_attendance_proof_pdf(
    record: AttendanceRecord, session_setting: SessionSetting | None
) -> bytes:
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    _width, height = A4
    y = height - inch

    p.setFont("Helvetica-Bold", 18)
    p.setFillColorRGB(0.1, 0.1, 0.5)
    p.drawString(inch, y, "QRTendify Attendance Verification Proof")
    y -= 0.5 * inch

    p.setFont("Helvetica-Bold", 12)
    p.setFillColorRGB(0, 0, 0)
    p.drawString(inch, y, f"Session: {record.session.title}")
    y -= 0.3 * inch
    org_name = (
        record.session.organization.name
        if record.session.organization
        else "Personal session"
    )
    p.drawString(inch, y, f"Organization: {org_name}")
    y -= 0.6 * inch

    p.setFont("Helvetica-Bold", 11)
    p.drawString(inch, y, "Attendee Details:")
    y -= 0.3 * inch

    p.setFont("Helvetica", 10)
    p.drawString(inch, y, f"Name: {record.user.first_name} {record.user.last_name}")
    y -= 0.3 * inch
    p.drawString(inch, y, f"Email: {record.user.email}")
    y -= 0.5 * inch

    p.setFont("Helvetica-Bold", 11)
    p.drawString(inch, y, "Check-in Status:")
    y -= 0.3 * inch

    p.setFont("Helvetica", 10)
    p.drawString(inch, y, f"Status: VERIFIED (Method: {record.check_in_method})")
    y -= 0.3 * inch
    p.drawString(
        inch, y, f"Check-in Time: {_date_format(record.check_in_time, 'j M Y, H:i:s')}"
    )
    y -= 0.3 * inch
    p.drawString(inch, y, f"Device IP: {record.device_ip}")
    y -= 0.5 * inch

    if session_setting and session_setting.is_location_required:
        p.setFont("Helvetica-Bold", 11)
        p.drawString(inch, y, "Geolocation Verification:")
        y -= 0.3 * inch

        location_data = "N/A - Location data not recorded"
        if record.devicelog and record.devicelog.latitude is not None:
            latitude_str = f"{record.devicelog.latitude:.6f}"
            longitude_str = f"{record.devicelog.longitude:.6f}"
            location_data = f"Lat: {latitude_str}, Lon: {longitude_str}"

        p.setFont("Helvetica", 10)
        p.drawString(inch, y, location_data)
        y -= 0.3 * inch

    p.setFont("Helvetica-Oblique", 8)
    p.drawString(
        inch,
        0.5 * inch,
        f"Proof ID: {record.pk} | Generated by QRTendify on {_date_format(timezone.now(), 'j M Y')}",
    )

    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer.getvalue()


def build_attendance_report_pdf(
    session: Session, session_setting: SessionSetting, records
) -> bytes:
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    y_position = height - inch
    line_height = 0.3 * inch
    max_lines_per_page = int((height - 2 * inch) / line_height)
    row_count = 0

    p.setFont("Helvetica-Bold", 14)
    p.drawString(inch, height - inch, f"Attendance Report: {session.title}")
    p.setFont("Helvetica", 10)
    org_name = session.organization.name if session.organization else "Personal session"
    p.drawString(inch, height - 1.3 * inch, f"Organization: {org_name}")
    p.drawString(
        inch, height - 1.6 * inch, f"Date: {_date_format(timezone.now(), 'j M Y')}"
    )

    col_name = 0.5 * inch
    col_email = 2.0 * inch
    col_time = 3.8 * inch
    col_ip = 5.3 * inch
    col_geo = 6.5 * inch

    def draw_table_header(canvas_obj, current_y):
        canvas_obj.setFont("Helvetica-Bold", 10)
        canvas_obj.line(
            0.5 * inch,
            current_y + line_height / 3,
            width - 0.5 * inch,
            current_y + line_height / 3,
        )
        current_y -= line_height
        canvas_obj.drawString(col_name, current_y, "Name")
        canvas_obj.drawString(col_email, current_y, "Email")
        canvas_obj.drawString(col_time, current_y, "Time")
        canvas_obj.drawString(col_ip, current_y, "IP Address")
        if session_setting.is_location_required:
            canvas_obj.drawString(col_geo, current_y, "Geolocation")
        canvas_obj.line(
            0.5 * inch,
            current_y - line_height / 3,
            width - 0.5 * inch,
            current_y - line_height / 3,
        )
        return current_y - line_height / 2

    y_position = draw_table_header(p, height - 2.0 * inch)

    p.setFont("Helvetica", 9)
    for record in records:
        if row_count >= max_lines_per_page:
            p.showPage()
            y_position = height - inch
            row_count = 0
            y_position = draw_table_header(p, y_position)

        y_position -= line_height
        p.drawString(
            col_name, y_position, f"{record.user.first_name} {record.user.last_name}"
        )
        p.drawString(col_email, y_position, record.user.email)
        p.drawString(
            col_time, y_position, _date_format(record.check_in_time, "H:i:s, j M")
        )
        p.drawString(col_ip, y_position, record.device_ip or "")

        if session_setting.is_location_required:
            location_data = "N/A"
            if record.devicelog and record.devicelog.latitude is not None:
                latitude_str = f"{record.devicelog.latitude:.4f}"
                longitude_str = f"{record.devicelog.longitude:.4f}"
                location_data = f"{latitude_str}, {longitude_str}"
            p.drawString(col_geo, y_position, location_data)

        row_count += 1

    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer.getvalue()
